name: pet_moment
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  firebase_core: ^3.8.1
  intl: ^0.20.1
  kakao_flutter_sdk: ^1.9.6
  photofilters: ^3.0.1
  lottie: ^3.2.0
  camera: ^0.11.0+2
  image: ^3.3.0
  google_sign_in: ^6.2.2
  the_apple_sign_in: ^1.1.1
  table_calendar: ^3.2.0
  firebase_storage: ^12.4.0
  font_awesome_flutter: ^10.8.0
  multi_image_picker2: ^5.0.02
  provider: ^6.1.2
  flutter_gif: ^0.0.4
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^18.0.1
  turn_page_transition: ^0.4.0
  shimmer: ^3.0.0
  liquid_swipe: ^3.1.0
  photo_manager: ^3.6.4
  image_gallery_saver: ^2.0.3
  gif_view: ^1.0.0
  flutter_image_compress: ^2.4.0
  pdf: ^3.8.4
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/co1.png
    - assets/co2.png
    - assets/co3.png
    - assets/co4.png
    - .env.local

  fonts:
    - family: Pretendard Variable
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf
    - family: HS유지체
      fonts:
        - asset: assets/fonts/HS유지체.ttf
